-- Generated by node scripts/export-checkout-catalog.cjs. Run after the orders migration.
begin;
update private.checkout_products set active=false;
insert into private.checkout_products(id,data,active) values
(1,'{"title":"Legging Sculpt Pure Waist","image":"/products/legging-sculpt-frente.jpg","price_cents":48000,"sizes":["PP","P","M","G","GG"],"colors":["Obsidian Black","Sage Olive","Cashmere Dune"]}'::jsonb,true),
(2,'{"title":"Top Studio Halter Neck Ribbed","image":"/products/top-sage-frente.jpg","price_cents":32000,"sizes":["PP","P","M","G"],"colors":["Sage Olive","Obsidian Black","Cloud Silk"]}'::jsonb,true),
(3,'{"title":"Jaqueta Bomber FeatherTouch Alfaiataria","image":"/products/bomber-taupe-frente.jpg","price_cents":79000,"sizes":["P","M","G"],"colors":["Cashmere Dune","Obsidian Black"]}'::jsonb,true),
(4,'{"title":"Macacão SilkAir One-Piece Catsuit","image":"/products/onesie-mineral-frente.jpg","price_cents":68000,"sizes":["PP","P","M","G"],"colors":["Deep Mineral","Obsidian Black"]}'::jsonb,true),
(5,'{"title":"Saia Plissada Court Tennis Skirt","image":"/products/skirt-tennis-frente.jpg","price_cents":39000,"sizes":["PP","P","M","G"],"colors":["Cloud Silk","Sage Olive"]}'::jsonb,true),
(6,'{"title":"Meias Técnicas de Compressão Anatomic (Par)","image":"/products/fabric-macro.jpg","price_cents":8900,"sizes":["Único"],"colors":["Cloud Silk","Obsidian Black"]}'::jsonb,true),
(7,'{"title":"STUW Mocha Sculpt Set","image":"/products/STUW-Mocha Sculpt-Set-frente.png","price_cents":69000,"sizes":["PP","P","M","G","GG"],"colors":["Mocha"]}'::jsonb,true),
(8,'{"title":"STUW Run Set — Mauve","image":"/products/STUW_Run_Set-Mauve-frente.png","price_cents":49000,"sizes":["PP","P","M","G","GG"],"colors":["Mauve"]}'::jsonb,true),
(10,'{"title":"STUW Move Zip Set","image":"/products/STUW-Move-Zip-Set-frente.png","price_cents":69000,"sizes":["PP","P","M","G","GG"],"colors":["Black"]}'::jsonb,true),
(11,'{"title":"STUW Studio Half-Zip Set","image":"/products/STUW-Studio Half-Zip-Set-frente.png","price_cents":59000,"sizes":["PP","P","M","G","GG"],"colors":["Off-White / Mocha"]}'::jsonb,true),
(12,'{"title":"STUW Active Run Set","image":"/products/STUW-Active-Run-Set-frente.png","price_cents":45000,"sizes":["PP","P","M","G","GG"],"colors":["Black"]}'::jsonb,true),
(13,'{"title":"STUW Sculpt Set Mocha","image":"/products/STUW-Sculpt-Set-Mocha-frente.png","price_cents":65000,"sizes":["PP","P","M","G","GG"],"colors":["Mocha"]}'::jsonb,true)
on conflict(id) do update set data=excluded.data,active=true;
commit;
