begin;

-- Private editorial documents include cost, fiscal and ERP information. Public reads use
-- only the explicit storefront projection, never the document or audit snapshots.
create table public.admin_products (
 id integer generated by default as identity (start with 1000000) primary key,
 document jsonb not null check (jsonb_typeof(document) = 'object' and octet_length(document::text) <= 250000),
 revision integer not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 created_by uuid references auth.users(id) on delete set null,
 updated_by uuid references auth.users(id) on delete set null,
 deleted_at timestamptz
);
create index admin_products_updated_idx on public.admin_products(updated_at desc);
create index admin_products_creator_idx on public.admin_products(created_by);
create index admin_products_editor_idx on public.admin_products(updated_by);
alter table public.admin_products enable row level security;
revoke all on public.admin_products from public, anon, authenticated;
grant select on public.admin_products to authenticated;
create policy products_admin_read on public.admin_products for select to authenticated using ((select public.is_admin()));

create table private.product_slugs (
 slug text primary key check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and length(slug) <= 160),
 product_id integer not null references public.admin_products(id) on delete restrict
);
create index product_slugs_product_idx on private.product_slugs(product_id);
create table private.product_colors (
 product_id integer not null references public.admin_products(id) on delete restrict,
 slug text not null, data jsonb not null, position integer not null check(position >= 0),
 primary key(product_id,slug)
);
create table private.product_skus (
 code text primary key check(code ~ '^[A-Z0-9_-]{1,64}$'),
 product_id integer not null,
 color_slug text not null,
 size text not null check(size in ('PP','P','M','G','GG','Único')),
 gtin text unique check(gtin is null or gtin ~ '^(\d{8}|\d{12}|\d{13}|\d{14})$'),
 stock integer not null check(stock between 0 and 1000000),
 price_cents bigint check(price_cents between 0 and 100000000),
 active boolean not null,
 unique(product_id,color_slug,size),
 foreign key(product_id,color_slug) references private.product_colors(product_id,slug) on delete cascade
);
create table private.product_audit (
 id bigint generated always as identity primary key,
 product_id integer not null references public.admin_products(id),
 actor_id uuid references auth.users(id) on delete set null,
 revision integer not null, document jsonb not null, created_at timestamptz not null default now(),
 unique(product_id,revision)
);
-- Keep identifiers reserved while older published versions or order snapshots
-- still refer to them, even when the current draft removes a SKU.
create table private.product_identifiers (
 kind text not null check(kind in ('sku','gtin')),
 value text not null,
 product_id integer not null references public.admin_products(id),
 color_slug text not null,
 size text not null,
 primary key(kind,value)
);
create index product_identifiers_product_idx on private.product_identifiers(product_id);
alter table private.product_identifiers enable row level security;
revoke all on private.product_identifiers from public,anon,authenticated;
create table private.product_wholesale_terms (
 product_id integer primary key references public.admin_products(id),
 price_cents bigint check(price_cents >= 0),
 minimum_quantity integer not null check(minimum_quantity > 0),
 pack text not null default ''
);
alter table private.product_wholesale_terms enable row level security;
revoke all on private.product_wholesale_terms from public,anon,authenticated;
create index product_audit_actor_idx on private.product_audit(actor_id);
alter table private.product_slugs enable row level security;
alter table private.product_colors enable row level security;
alter table private.product_skus enable row level security;
alter table private.product_audit enable row level security;
revoke all on private.product_slugs, private.product_colors, private.product_skus, private.product_audit from public,anon,authenticated;

-- Null payloads are tombstones: an inactive managed legacy item must not reappear
-- from the static fallback catalog. Drafts do not overwrite this table.
create table public.catalog_products (
 id integer primary key references public.admin_products(id),
 payload jsonb,
 publish_at timestamptz,
 aliases text[] not null default '{}'
);
alter table public.catalog_products enable row level security;
revoke all on public.catalog_products from public,anon,authenticated;
grant select on public.catalog_products to anon,authenticated;
create policy catalog_public_read on public.catalog_products for select to anon,authenticated using(true);

create function private.save_product(input_id integer, expected_revision integer, input_document jsonb, input_payload jsonb, legacy_slug text)
returns integer language plpgsql security definer set search_path = '' as $$
declare
 uid uuid := auth.uid(); pid integer := input_id; prev public.admin_products;
 c jsonb; s jsonb; pos integer := 0; next_revision integer; reserved_slug text;
begin
 if uid is null or not public.is_admin() then raise insufficient_privilege; end if;
 if expected_revision < 0 or expected_revision is null or input_document is null or jsonb_typeof(input_document) <> 'object'
 or coalesce(input_document->>'name','') = '' or coalesce(input_document->>'slug','') !~ '^[a-z0-9]+(-[a-z0-9]+)*$'
 or coalesce(input_document->>'status','') not in ('draft','active','inactive')
 or jsonb_typeof(input_document->'colors') is distinct from 'array'
 or jsonb_array_length(input_document->'colors') > 30 then raise exception 'Invalid product'; end if;
 if pid is null then
   if expected_revision <> 0 then raise exception 'Revision conflict' using errcode='40001'; end if;
   insert into public.admin_products(document,created_by,updated_by) values(input_document,uid,uid) returning id into pid;
 elsif expected_revision = 0 then
   if pid <= 0 or pid >= 1000000 then raise exception 'Invalid legacy identity'; end if;
   insert into public.admin_products(id,document,created_by,updated_by) values(pid,input_document,uid,uid);
 else
   select * into prev from public.admin_products where id=pid for update;
   if not found or prev.revision <> expected_revision or prev.deleted_at is not null then raise exception 'Revision conflict' using errcode='40001'; end if;
   update public.admin_products set document=input_document,revision=revision+1,updated_at=now(),updated_by=uid where id=pid;
 end if;
 for reserved_slug in select distinct unnest(array[input_document->>'slug', legacy_slug]) loop
   if reserved_slug is null then continue; end if;
   insert into private.product_slugs(slug,product_id) values(reserved_slug,pid)
     on conflict(slug) do update set product_id=excluded.product_id where private.product_slugs.product_id=excluded.product_id;
   if not found then raise unique_violation; end if;
 end loop;
 -- Atomic replacement; cross-product SKU/GTIN uniqueness is enforced by constraints.
 delete from private.product_colors where product_id=pid;
 for c in select value from jsonb_array_elements(input_document->'colors') loop
   insert into private.product_colors values(pid,c->>'slug',c-'skus',pos); pos := pos+1;
   for s in select value from jsonb_array_elements(c->'skus') loop
     insert into private.product_identifiers(kind,value,product_id,color_slug,size)
     values('sku',s->>'code',pid,c->>'slug',s->>'size')
     on conflict(kind,value) do update set product_id=excluded.product_id
     where private.product_identifiers.product_id=excluded.product_id and private.product_identifiers.color_slug=excluded.color_slug and private.product_identifiers.size=excluded.size;
     if not found then raise unique_violation; end if;
     if nullif(s->>'gtin','') is not null then
       insert into private.product_identifiers(kind,value,product_id,color_slug,size)
       values('gtin',s->>'gtin',pid,c->>'slug',s->>'size')
       on conflict(kind,value) do update set product_id=excluded.product_id
       where private.product_identifiers.product_id=excluded.product_id and private.product_identifiers.color_slug=excluded.color_slug and private.product_identifiers.size=excluded.size;
       if not found then raise unique_violation; end if;
     end if;
     insert into private.product_skus(code,product_id,color_slug,size,gtin,stock,price_cents,active)
       values(s->>'code',pid,c->>'slug',s->>'size',nullif(s->>'gtin',''),(s->>'stock')::integer,
         round((s->>'price')::numeric*100)::bigint,(s->>'active')::boolean);
   end loop;
 end loop;
 select revision into next_revision from public.admin_products where id=pid;
 insert into private.product_audit(product_id,actor_id,revision,document) values(pid,uid,next_revision,input_document);
 if input_document->>'status' <> 'draft' then
   if input_document->>'status' = 'active' and (input_payload is null or jsonb_typeof(input_payload->'regular') is distinct from 'object') then raise exception 'Missing public product'; end if;
   -- IDs are allocated here; never trust a client-provided ID in the projection.
   input_payload := jsonb_set(jsonb_set(input_payload,'{regular,id}',to_jsonb(pid)),'{promotion,id}',to_jsonb(pid));
   insert into public.catalog_products(id,payload,publish_at,aliases)
   values(pid,case when input_document->>'status'='active' then input_payload else null end,
     nullif(input_document->>'publishAt','')::timestamptz,
     array(select slug from private.product_slugs where product_id=pid))
   on conflict(id) do update set payload=excluded.payload,publish_at=excluded.publish_at,aliases=excluded.aliases;
   if input_document->>'status'='active' then
     insert into private.product_wholesale_terms(product_id,price_cents,minimum_quantity,pack)
     values(pid,round((input_document->>'wholesalePrice')::numeric*100),coalesce((input_document->>'wholesaleMinimum')::integer,1),coalesce(input_document->>'wholesalePack',''))
     on conflict(product_id) do update set price_cents=excluded.price_cents,minimum_quantity=excluded.minimum_quantity,pack=excluded.pack;
   end if;
 end if;
 return pid;
end;
$$;
revoke all on function private.save_product(integer,integer,jsonb,jsonb,text) from public,anon,authenticated;
grant usage on schema private to authenticated;
grant execute on function private.save_product(integer,integer,jsonb,jsonb,text) to authenticated;
create function public.save_product(input_id integer,expected_revision integer,input_document jsonb,input_payload jsonb,legacy_slug text default null)
returns integer language sql security invoker set search_path = '' as $$
 select private.save_product(input_id,expected_revision,input_document,input_payload,legacy_slug);
$$;
revoke all on function public.save_product(integer,integer,jsonb,jsonb,text) from public,anon;
grant execute on function public.save_product(integer,integer,jsonb,jsonb,text) to authenticated;

create function private.archive_product(input_id integer,expected_revision integer)
returns void language plpgsql security definer set search_path = '' as $$
declare p public.admin_products;
begin
 if auth.uid() is null or not public.is_admin() then raise insufficient_privilege; end if;
 select * into p from public.admin_products where id=input_id for update;
 if not found or p.revision<>expected_revision or p.deleted_at is not null then raise exception 'Revision conflict' using errcode='40001'; end if;
 update public.admin_products set deleted_at=now(),updated_at=now(),updated_by=auth.uid(),revision=revision+1 where id=input_id;
 insert into private.product_audit(product_id,actor_id,revision,document) values(input_id,auth.uid(),p.revision+1,p.document || jsonb_build_object('deletedAt',now()));
 insert into public.catalog_products(id,payload) values(input_id,null) on conflict(id) do update set payload=null;
end;
$$;
revoke all on function private.archive_product(integer,integer) from public,anon,authenticated;
grant execute on function private.archive_product(integer,integer) to authenticated;
create function public.archive_product(input_id integer,expected_revision integer) returns void language sql security invoker set search_path = '' as $$ select private.archive_product(input_id,expected_revision); $$;
revoke all on function public.archive_product(integer,integer) from public,anon;
grant execute on function public.archive_product(integer,integer) to authenticated;

-- Used by the existing demo checkout and quotation functions. Managed variants
-- are checked as an exact color/size pair, including current price and stock.
create function private.checkout_product_variant(pid integer, color_name text, size_name text, quantity integer)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare managed public.catalog_products; p jsonb; variant jsonb;
begin
 select * into managed from public.catalog_products where id=pid;
 if found then
   if managed.payload is null or managed.publish_at > now() then return null; end if;
   p := case when nullif(managed.payload->>'saleStart','')::timestamptz <= now() and now() < nullif(managed.payload->>'saleEnd','')::timestamptz then managed.payload->'promotion' else managed.payload->'regular' end;
   select value into variant from jsonb_array_elements(p->'variants') where value->>'color'=color_name and value->>'size'=size_name;
   if variant is null or (variant->>'stock')::integer < quantity then return null; end if;
   return jsonb_build_object('title',p->>'title','image',p->>'image','price_cents',round((variant->>'price')::numeric*100),'sizes',jsonb_build_array(size_name),'colors',jsonb_build_array(color_name));
 end if;
 select data into p from private.checkout_products where id=pid and active;
 return p;
end;
$$;
revoke all on function private.checkout_product_variant(integer,text,text,integer) from public,anon,authenticated;

create or replace function private.create_demo_order(request jsonb)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
 uid uuid := auth.uid();
 key uuid := (request->>'key')::uuid;
 existing uuid;
 oid uuid := gen_random_uuid();
 info jsonb := request->'information';
 line jsonb;
 product jsonb;
 snapshot jsonb := '[]';
 qty integer;
 price bigint;
 subtotal bigint := 0;
 shipping bigint;
 wrapping bigint := 0;
 discount bigint := 0;
 pix bigint := 0;
 rate numeric := 0;
 code text := upper(trim(coalesce(request->>'coupon','')));
 email text;
begin
 if uid is null then raise insufficient_privilege; end if;
 if key is null or request is null or octet_length(request::text) > 40000 then raise exception 'Invalid request'; end if;
 -- Serialize retries for this account, including simultaneous submissions.
 perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));
 select id into existing from public.orders where user_id = uid and request_key = key;
 if found then return existing; end if;
 if jsonb_typeof(request->'items') is distinct from 'array'
 or jsonb_array_length(request->'items') not between 1 and 50 then raise exception 'Invalid cart'; end if;
 if jsonb_typeof(info) is distinct from 'object' or info->>'postalCode' is null
 or (info->>'postalCode') !~ '^\d{5}-?\d{3}$'
 or coalesce(info->>'state','') !~ '^(AC|AL|AP|AM|BA|CE|DF|ES|GO|MA|MT|MS|MG|PA|PB|PR|PE|PI|RJ|RN|RS|RO|RR|SC|SP|SE|TO)$'
 or regexp_replace(coalesce(info->>'phone',''),'\D','','g') !~ '^\d{10,11}$'
 then raise exception 'Invalid address'; end if;
 foreach email in array array['firstName','lastName','street','number','district','city'] loop
  if char_length(trim(coalesce(info->>email,''))) not between 1 and 200 then raise exception 'Invalid address'; end if;
 end loop;
 if coalesce(request->>'payment','') not in ('pix','card')
 or coalesce((request->>'installments')::integer,0) not between 1 and 6
 or coalesce(request->>'shipping','') not in ('standard','express') then raise exception 'Invalid checkout'; end if;
 if exists(select 1 from jsonb_array_elements(request->'items') i group by i->>'id',i->>'color',i->>'size' having count(*)>1) then raise exception 'Duplicate variant'; end if;
 for line in select value from jsonb_array_elements(request->'items') loop
  qty := (line->>'qty')::integer;
  if qty is null or qty not between 1 and 99 then raise exception 'Invalid quantity'; end if;
  product := private.checkout_product_variant((line->>'id')::integer,line->>'color',line->>'size',qty);
  if product is null or not (product->'sizes' ? coalesce(line->>'size',''))
    or not (product->'colors' ? coalesce(line->>'color','')) then raise exception 'Invalid variant'; end if;
  price := (product->>'price_cents')::bigint;
  subtotal := subtotal + price * qty;
  snapshot := snapshot || jsonb_build_array(jsonb_build_object('id',line->'id','title',product->>'title',
   'image',product->>'image','size',line->>'size','color',line->>'color','qty',qty,'price_cents',price));
 end loop;
 shipping := case when request->>'shipping' = 'express' then 4500 when subtotal >= 49900 then 0 else 2800 end;
 if (request->>'gift')::boolean and (request->>'giftWrap')::boolean then wrapping := 3500; end if;
 select u.email into email from auth.users u where u.id = uid;
 insert into public.orders(id,user_id,number,status,total_cents,is_demo,request_key,customer_name,customer_email,
 delivery,items,payment_method,installments,gift,subtotal_cents,shipping_cents,gift_cents,coupon_code,shipping_name,shipping_estimate)
 values(oid,uid,'TESTE-' || upper(replace(oid::text,'-','')),'pending',subtotal+shipping+wrapping,true,key,
 trim(info->>'firstName') || ' ' || trim(info->>'lastName'),email,
 jsonb_build_object('street',info->>'street','number',info->>'number','complement',coalesce(info->>'complement',''),
 'district',info->>'district','city',info->>'city','state',info->>'state','postalCode',info->>'postalCode','phone',info->>'phone'),snapshot,request->>'payment',
 case when request->>'payment' = 'pix' then 1 else (request->>'installments')::integer end,
 coalesce((request->>'gift')::boolean,false),subtotal,shipping,wrapping,code,
 case when request->>'shipping' = 'express' then 'Entrega expressa' else 'Entrega econômica' end,
 case when request->>'shipping' = 'express' then '2 a 3 dias úteis' else '5 a 8 dias úteis' end);
 if code <> '' then
  discount := private.record_coupon_use(code,oid);
  select percent into rate from public.coupon_redemptions where order_id = oid;
 end if;
 if request->>'payment' = 'pix' then pix := round((subtotal-round(subtotal*rate/100))*0.05); end if;
 if (request->>'expectedTotal')::bigint is distinct from subtotal+shipping+wrapping-discount-pix then
  raise exception 'Total changed';
 end if;
 update public.orders set total_cents=total_cents-pix,discount_cents=discount,pix_discount_cents=pix where id=oid;
 insert into public.order_events(order_id,actor_id,status,note) values(oid,uid,'pending','Pedido de teste registrado. Nenhuma cobrança realizada.');
 return oid;
end; $$;

create or replace function private.create_wholesale_quote(request jsonb) returns uuid
language plpgsql security definer set search_path='' as $$
declare
 uid uuid:=auth.uid();
 request_id uuid:=(request->>'key')::uuid;
 existing uuid;
 quote_id uuid:=gen_random_uuid();
 minimum integer;
 line jsonb;
 product jsonb;
 snapshot jsonb:='[]';
 qty integer;
 total integer:=0;
 email text;
 terms private.product_wholesale_terms;
 model_qty integer;
begin
 if uid is null then raise insufficient_privilege; end if;
 if request_id is null or request is null or octet_length(request::text)>40000 then raise exception 'Invalid request'; end if;
 perform pg_advisory_xact_lock(hashtextextended('wholesale:'||uid::text,0));
 select id into existing from public.wholesale_quotes where user_id=uid and request_key=request_id;
 if found then return existing; end if;
 select minimum_quantity into minimum from public.wholesale_settings where id=true for share;
 if not found then raise exception 'Wholesale unavailable'; end if;
 if jsonb_typeof(request->'items') is distinct from 'array' or jsonb_array_length(request->'items') not between 1 and 50 then raise exception 'Invalid items'; end if;
 for line in select value from jsonb_array_elements(request->'items') loop
  if coalesce(line->>'qty','') !~ '^[0-9]{1,4}$' then raise exception 'Invalid quantity'; end if;
  qty:=(line->>'qty')::integer;
  if qty<1 then raise exception 'Invalid quantity'; end if;
  select sum((value->>'qty')::integer) into model_qty from jsonb_array_elements(request->'items') where value->>'id'=line->>'id' and value->>'color'=line->>'color' and value->>'size'=line->>'size';
  product := private.checkout_product_variant((line->>'id')::integer,line->>'color',line->>'size',model_qty);
  if product is null or not (product->'sizes' ? coalesce(line->>'size','')) or not (product->'colors' ? coalesce(line->>'color','')) then raise exception 'Invalid variant'; end if;
  total:=total+qty;
  select * into terms from private.product_wholesale_terms where product_id=(line->>'id')::integer;
  if found then
    select sum((value->>'qty')::integer) into model_qty from jsonb_array_elements(request->'items') where value->>'id'=line->>'id';
    if model_qty < terms.minimum_quantity then raise exception 'Product minimum: %',terms.minimum_quantity; end if;
  end if;
  snapshot:=snapshot||jsonb_build_array(jsonb_build_object('id',line->'id','title',product->>'title','image',product->>'image','size',line->>'size','color',line->>'color','qty',qty,'wholesale_price_cents',terms.price_cents,'wholesale_minimum',terms.minimum_quantity,'wholesale_pack',terms.pack));
 end loop;
 if total<minimum then raise exception 'Minimum quantity: %',minimum; end if;
 select u.email into email from auth.users u where u.id=uid;
 insert into public.wholesale_quotes(id,user_id,request_key,number,customer_name,customer_email,phone,company,cnpj,notes,items,quantity,minimum_quantity)
 values(quote_id,uid,request_id,'ATC-'||upper(replace(quote_id::text,'-','')),trim(request->>'name'),email,
 request->>'phone',trim(coalesce(request->>'company','')),coalesce(request->>'cnpj',''),trim(coalesce(request->>'notes','')),snapshot,total,minimum);
 insert into public.wholesale_quote_events(quote_id,actor_id,status,note) values(quote_id,uid,'received','Solicitação registrada. Valores e disponibilidade sujeitos à negociação.');
 return quote_id;
end; $$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp','image/avif']);
create policy product_assets_admin_read on storage.objects for select to authenticated
 using(bucket_id='product-images' and (select public.is_admin()));
create policy product_assets_admin_upload on storage.objects for insert to authenticated
 with check(bucket_id='product-images' and name ~ '^[0-9a-f-]{36}\.(jpg|png|webp|avif)$' and (select public.is_admin()));
-- Immutable uploads. Referenced files cannot be replaced/deleted through the client.

commit;
